const mongoose = require('mongoose')

const contact = new mongoose.Schema({
    //find out more about id field. It is autogenerated for each object

    firstname:{
        type:String,
        required:true,
    },
    lastname:{
        type: String,
        required:true,
    },
    phone:{
        type:String,
        required:true,
    },
    mobile:{
        type:String,
        required:true,
    },
    remarks:{
        type:String,
        required:true,
    },
    email:{
        type:String,
        required:true,
    }
})

module.exports= mongoose.model('Contact', contact);