const mongoose = require('mongoose')

const state = new mongoose.Schema({
    //find out more about id field. It is autogenerated for each object

    name:{
        type:String,
        required:true,
    },
    capital:{
        type:String,
        required:true,
    },
    code:{
        type:String,
        required:true,
    },
    //relies on Country country object mapping
    countryid:{
        type: String,
        required:true,
    },
    details:{
        type:String,
        required:true,
    }
    
})

module.exports= mongoose.model('State', state);