const mongoose = require('mongoose')

const commonObject = new mongoose.Schema({
    //find out more about id field. It is autogenerated for each object

    descriptions:{
        type:String,
        required:true,
    },
    details:{
        type: String,
        required:true,
    }
})

module.exports= mongoose.model('CommonObject', commonObject);