const mongoose = require('mongoose')

const module = new mongoose.Schema({
    //find out more about id field. It is autogenerated for each object
   
    //extends CommonObject
})

module.exports= mongoose.model('Module', module);