const mongoose = require('mongoose')

const supplier = new mongoose.Schema({
    //find out more about id field. It is autogenerated for each object

    name:{
        type:String,
        required:true,
    },
    address:{
        type: Number,
        required:true,
    },
    
    city:{
        type:String,
        required:true,
    },
    phone:{
        type:String,
        required:true,
    },
    mobile:{
        type:String,
        required:true,
    },
    website:{
        type:String,
        required:true,
    },
    email:{
        type:String,
        required:true,
    },
    //relies on Country country object mapping
     countryid:{
        type:String,
        required:true,
    },

     //relies on State state object mapping
    stateid:{
        type:String,
        required:true,
    },
    details:{
        type:String,
        required:true,
    },
})

module.exports= mongoose.model('Supplier', supplier);