const mongoose = require("mongoose");

const invoice = new mongoose.Schema({
  //find out more about id field. It is autogenerated for each object

  invoiceDate: {
    type: String,
    required: true,
  },
  //referenced from InvoiceStatus invoiceStatus model(int)
  invoicestatusid: {
    type: Date,
    required: true,
  },
  
  //referenced from CLient client model(int)
  clientid: {
    type: String,
    required: true,
  },

  remarks: {
    type: String,
    required: true,
  }

});

module.exports = mongoose.model("Invoice", invoice);