const mongoose = require("mongoose");

const ticket = new mongoose.Schema({
  //find out more about id field. It is autogenerated for each object

  description: {
    type: String,
    required: true,
  },

  amount: {
    type: String,
    required: true,
  },

  transactionDate: {
    type: Date,
    required: true,
  },
  //referenced from TransactionStatus  transactionStatus model
  transactionstatusid: {
    type: String,
    required: true,
  },
  //referenced from TransactionType transactionType model
  transactiontypeid: {
    type: String,
    required: true,
  },
  //referenced from Employee employee model
  accountantid: {
    type: String,
    required: true,
  },
  
  remarks: {
    type: String,
    required: true,
  },
});

module.exports = mongoose.model("Ticket", ticket);
