const mongoose = require('mongoose')

const employeeType = new mongoose.Schema({
    //find out more about id field. It is autogenerated for each object
    //Extended from CommonObjec
})

module.exports = mongoose.model('EmployeeType', employeeType);