const mongoose = require("mongoose");

const projectHire = new mongoose.Schema({
  //find out more about id field. It is autogenerated for each object

  //will be referenced to from Project model
  projectid: {
    type: String,
    required: true,
  },

  dateHired: {
    type: Date,
    required: true,
  },
  
  dueDate: {
    type: Date,
    required: true,
  },
  
  //referenced from Client client model
  clientid: {
    type: String,
    required: true,
  },

  price: {
    type: String,
    required: true,
  },

  remarks: {
    type: String,
    required: true,
  }

});

module.exports = mongoose.model("ProjectHire", projectHire);