const mongoose = require('mongoose')

const country = new mongoose.Schema({
    //find out more about id field. It is autogenerated for each object

    code:{
        type:String,
        required:true,
    },
    capital:{
        type:String,
        required:true,
    },
    description:{
        type:String,
        required:true,
    },
    nationality:{
        type:String,
        required:true,
    },
    continent:{
        type:String,
        required:true,
    }
})

module.exports= mongoose.model('Country', country);