const mongoose = require('mongoose')

const location = new mongoose.Schema({
    //find out more about id field. It is autogenerated for each object

    description:{
        type:String,
        required:true,
    },
    //relies on Country country object mapping
    countryid:{
        type: String,
        required:true,
    },
     //relies on State state object mapping
    stateid:{
        type:String,
        required:true,
    },
    city:{
        type:String,
        required:true,
    },
    address:{
        type:String,
        required:true,
    }
})

module.exports= mongoose.model('Location', location);