const mongoose = require('mongoose')

const department = new mongoose.Schema({
    //find out more about id field. It is autogenerated for each object
    description:{
        type:String,
        required:true,
    },
    //referenced form Employee employee model
    managerid:{
        type:String,
        required:true,
    },
})

module.exports = mongoose.model('Department', department);