const mongoose = require("mongoose");

const ticketStatus = new mongoose.Schema({
  //find out more about id field. It is autogenerated for each object

  //Extended from Common Object
})

module.exports = mongoose.model("TicketStatus", ticketStatus);