const mongoose = require("mongoose");

const ticket = new mongoose.Schema({
  //find out more about id field. It is autogenerated for each object

  description: {
    type: String,
    required: true,
  },
  //referenced from Employee employee model
  raisedbyid: {
    type: String,
    required: true,
  },
  //referenced from TicketStatus ticketStatus model
  ticketstatusid: {
    type: String,
    required: true,
  },

  ticketDate: {
    type: Date,
    required: true,
  }

});

module.exports = mongoose.model("Ticket", ticket);