const mongoose = require('mongoose')

const supplier = new mongoose.Schema({
    //find out more about id field. It is autogenerated for each object

    username:{
        type:String,
        required:true,
    },
    password:{
        type: String,
        required:true,
    },
    
    firstname:{
        type:String,
        required:true,
    },
    lastname:{
        type:String,
        required:true,
    },

    //Set<Role> roles = new HashSet<>()
    //user_role // user_id//role_id
    //roles assigned to a user
    roles:{
        type:String(HashSet),
        required:true,
    }
})

module.exports= mongoose.model('Supplier', supplier);