const mongoose = require('mongoose')

const employee = new mongoose.Schema({
    //find out more about id field. It is autogenerated for each object

    //referenced form employeeType model
    employeetypeid:{
        type:String,
        required:true,
    },
    //referenced from title model
    titleid:{
        type:String,
        required:true,
    },
    //referenced from gender model
    genderid:{
        type:String,
        required:true,
    },
    //referenced from maritalStatus model
    maritalStatusid:{
        type: String,
        required:true,
    },
    //will be used as same username for login and profile
    username:{
        type:String,
        required:true,
    },
    hireDate:{
        type:Date,
        required:true,
    },
    dateOfBirth:{
        type:Date,
        required:true,
    },
    firstname:{
        type:String,
        required:true,
    },
    othername:{
        type:String,
        required:true,
    },
    initials:{
        type:String,
        required:true,
    },
    socialSecurityNumber:{
        type:String,
        required:true,
    },
    city:{
        type:String,
        required:true,
    },
    address:{
        type:String,
        required:true,
    },
    phone:{
        type:String,
        required:true,
    },
    mobile:{
        type:String,
        required:true,
    },
    email:{
        type:String,
        required:true,
    },
    //list referenced from Projects model
    // projects:{
    //     type:String(List),
    //     required:true,
    // },

    //referenced from job model
    jobroleid:{
        type:String,
        required:true,
    },
    //referenced from employeeStatus model
    employeestatusid:{
        type:String,
        required:true,
    },
    //referenced from country model
    countryid:{
        type:String,
        required:true,
    },
    
    //referenced from state model
    stateid:{
        type:String,
        required:true,
    }    
})

module.exports= mongoose.model('Employee', employee);