const mongoose = require('mongoose')

const jobRole = new mongoose.Schema({
    //find out more about id field. It is autogenerated for each object
    //Extended from CommonObject
})

module.exports = mongoose.model('JobRole', jobRole);